version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: ./mvnw spring-boot:run

  db:
    image: postgres:latest
    container_name: postgres-todo
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_todoapp:/var/lib/postgresql/data

volumes:
  postgres_todoapp: