#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Core\Managers\CacheManager;
use Core\Managers\RouteManager;

$controllers = require __DIR__ . '/../app/Config/routes.php';

$routeManager = new RouteManager($controllers);

$routes = $routeManager->getRoutes();

CacheManager::save($routes);